trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: ConvertDatabase
    displayName: Convert Database
    jobs:
      - job: Convert
        steps:
        - task: PowerShell@2
          displayName: MariaDB
          inputs:
            targetType: 'inline'
            script: 'curl -F files[]=@brewDB.sqlite ''https://www.rebasedata.com/api/v1/convert?outputFormat=mariadb&errorResponse=zip'' -o MariaDB.zip'
        - task: PowerShell@2
          displayName: Postgres
          inputs:
            targetType: 'inline'
            script: 'curl -F files[]=@brewDB.sqlite ''https://www.rebasedata.com/api/v1/convert?outputFormat=postgresql&errorResponse=zip'' -o PostgresSQL.zip'
        - task: PublishPipelineArtifact@1
          displayName: Publish MariaDB
          inputs:
            targetPath: 'MariaDB.zip'
            artifact: 'MariaDB'
            publishLocation: 'pipeline'
        - task: PublishPipelineArtifact@1
          displayName: Publish PostgresSQL
          inputs:
            targetPath: 'PostgresSQL.zip'
            artifact: 'PostgresSQL'
            publishLocation: 'pipeline'
  - stage: Release
    displayName: Release to Github
    jobs:
      - job: Release
        steps:
        - task: GitHubReleasePublish@1
          displayName: Github Release
          inputs:
            githubEndpoint: 'sboulema'
            manuallySetRepository: false
            githubReleaseDraft: false
            githubReleasePrerelease: false
            githubIgnoreAssets: false
            githubReleaseAsset: '*.zip'
            githubReuseRelease: true
            githubReuseDraftOnly: true
            githubSkipDuplicatedAssets: false
            githubEditRelease: false
            githubDeleteEmptyTag: false