name: BrewDB

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Convert to MariaDB
        uses: enflo/curl-action@master
        with:
          curl: -F files[]=@brewDB.sqlite https://www.rebasedata.com/api/v1/convert?outputFormat=mariadb&errorResponse=zip -o MariaDB.zip

      - name: Convert to Postgres
        uses: enflo/curl-action@master
        with:
          curl: -F files[]=@brewDB.sqlite https://www.rebasedata.com/api/v1/convert?outputFormat=postgresql&errorResponse=zip -o Postgres.zip      

      - name: Convert to MySQL
        uses: enflo/curl-action@master
        with:
          curl: -F files[]=@brewDB.sqlite https://www.rebasedata.com/api/v1/convert?outputFormat=mysql&errorResponse=zip -o MySQL.zip  

      - name: Convert to Excel
        uses: enflo/curl-action@master
        with:
          curl: -F files[]=@brewDB.sqlite https://www.rebasedata.com/api/v1/convert?outputFormat=xlsx&errorResponse=zip -o Excel.zip  

      - name: Tag release
        id: tag_release
        uses: mathieudutour/github-tag-action@v6.0
        with:
          custom_tag: '${{ github.run_number }}'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_release.outputs.new_tag }}
          name: ${{ steps.tag_release.outputs.new_tag }}
          body: ${{ steps.tag_release.outputs.changelog }}
          artifacts: "**/*.zip"