name: BrewDB

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Convert to MariaDB
        uses: wei/curl@v1
        with:
          args: --upload-file brewDB.sqlite https://www.rebasedata.com/api/v1/convert?outputFormat=mariadb&errorResponse=zip -o MariaDB.zip
  
      - name: Convert to Postgres
        uses: wei/curl@v1
        with:
          args: --upload-file brewDB.sqlite https://www.rebasedata.com/api/v1/convert?outputFormat=postgresql&errorResponse=zip -o Postgres.zip

      - name: Convert to MySQL
        uses: wei/curl@v1
        with:
          args: --upload-file brewDB.sqlite https://www.rebasedata.com/api/v1/convert?outputFormat=mysql&errorResponse=zip -o MySQL.zip

      - name: Convert to Excel
        uses: wei/curl@v1
        with:
          args: --upload-file brewDB.sqlite https://www.rebasedata.com/api/v1/convert?outputFormat=xlsx&errorResponse=zip -o Excel.zip

      - name: Tag release
        id: tag_release
        uses: mathieudutour/github-tag-action@v5.6
        with:
          custom_tag: '${{ github.run_number }}'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_release.outputs.new_tag }}
          name: ${{ steps.tag_release.outputs.new_tag }}
          body: ${{ steps.tag_release.outputs.changelog }}
          artifacts: "**/*.zip"